FROM node:latest AS build

WORKDIR /app

COPY package*.json ./

RUN npm install && npm install -g vite

COPY . .

RUN mkdir -p /app/dist && chmod -R 777 /app/dist

RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
